---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux
spec:
  interval: 30s
  ref:
    branch: deploy
  url: https://github.com/Meghana7777777/flux-cd-repo.git
